trigger:
  branches:
    include:
    - master

stages:
- stage: CI
  jobs:
  - job: Build

    pool:
      vmImage: 'Ubuntu-latest'

    steps:
    - powershell: npm install
      displayName: 'npm install project'

    - powershell: npm run build-prod
      displayName: 'ng build for prod'

    - task: CopyFiles@2
      displayName: 'copy dist folder to artifacts staging folder'
      inputs:
        sourceFolder: dist/codestreamcoza2
        contents: '**'
        targetFolder: $(Build.ArtifactStagingDirectory)
        cleanTargetFolder: true

    - task: PublishBuildArtifacts@1
      displayName: 'publish dist folder to artifacts'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'files-to-deploy'

- stage: PROD
  dependsOn: CI
  condition: succeeded()

  jobs:
  - deployment: DeployWebApp
    displayName: Deploy Angular App
    pool:
      vmImage: "Windows-2019"

    environment: PROD
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Pipeline Artifact'
            inputs:
              artifactName: 'files-to-deploy'
              targetPath: '$(System.DefaultWorkingDirectory)\files-to-deploy'

          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens in **/main*.js **/microsoft-identity-association.json'
            inputs:
              rootDirectory: '$(System.DefaultWorkingDirectory)\files-to-deploy'
              targetFiles: |
                **/main*.js
              escapeType: none

          - task: AzureCLI@1
            displayName: 'Delete Old Files'
            inputs:
              azureSubscription: 'CodeStream Primary Account (9bc0617b-0bc8-47b1-974f-0df5a7ce7ac8)'
              scriptLocation: inlineScript
              inlineScript: |
                az storage blob delete-batch --source $web --account-name $(StorageAccountName) --output table

          - task: AzureFileCopy@4
            displayName: 'Copy New Files to Storage Account'
            inputs:
              SourcePath: '$(System.DefaultWorkingDirectory)\files-to-deploy\*'
              azureSubscription: 'CodeStream Primary Account (9bc0617b-0bc8-47b1-974f-0df5a7ce7ac8)'
              Destination: AzureBlob
              storage: '$(StorageAccountName)'
              ContainerName: '$web'

          - task: AzureFileCopy@4
            displayName: "Overwrite new js files with correct Content Type"
            inputs:
              SourcePath: '$(System.DefaultWorkingDirectory)\files-to-deploy\*.js'
              azureSubscription: 'CodeStream Primary Account (9bc0617b-0bc8-47b1-974f-0df5a7ce7ac8)'
              Destination: 'AzureBlob'
              storage: '$(StorageAccountName)'
              ContainerName: '$web'
              AdditionalArgumentsForBlobCopy: '--content-type "application/javascript"'

          - task: staff0rd.tfx-cloudflare-purge.custom-build-release-task.tfx-cloudflare-purge@1
            displayName: 'Purge Cloudflare cache'
            inputs:
              username: 'allen@codestream.co.za'
              apikey: '$(CloudflareGlobalApiKey)'
              zonename: '$(CloudflareZoneName)'
